import { test, expect } from '@playwright/test';
import { login, snap, navigateTo, waitForAngular, waitForSpinner } from './helpers';

const S = '02-template-management';

test.describe('2. Design Studio — Template Management', () => {
  test.beforeEach(async ({ page }, testInfo) => {
    await login(page, testInfo);
  });

  test('2.1 View Template Library', async ({ page }, testInfo) => {
    await navigateTo(page, '/templates', testInfo);
    await waitForSpinner(page);
    await snap(page, S, '2.1-template-library', testInfo);
  });

  test('2.2 Create Template via Wizard', async ({ page }, testInfo) => {
    await navigateTo(page, '/templates/new', testInfo);
    await waitForSpinner(page);
    await snap(page, S, '2.2-wizard-step1-basic-info', testInfo);

    // Step 1: Basic Info
    const nameInput = page.locator('input[formcontrolname="name"], input[name="name"]').first();
    if (await nameInput.isVisible()) {
      await nameInput.fill('Playwright Test Template');
    }
    const descInput = page.locator('input[formcontrolname="description"], textarea[formcontrolname="description"]').first();
    if (await descInput.isVisible()) {
      await descInput.fill('Auto-generated by Playwright');
    }
    await snap(page, S, '2.2-wizard-step1-filled', testInfo);

    // Click Next
    const nextBtn = page.locator('button:has-text("Next"), button:has-text("التالي")').first();
    if (await nextBtn.isVisible() && await nextBtn.isEnabled()) {
      await nextBtn.click();
      await waitForAngular(page);
      await snap(page, S, '2.2-wizard-step2-locale', testInfo);

      // Step 2: Click Next again
      const nextBtn2 = page.locator('button:has-text("Next"), button:has-text("التالي")').first();
      if (await nextBtn2.isVisible() && await nextBtn2.isEnabled()) {
        await nextBtn2.click();
        await waitForAngular(page);
        await snap(page, S, '2.2-wizard-step3-page-setup', testInfo);

        // Step 3: Click Next again
        const nextBtn3 = page.locator('button:has-text("Next"), button:has-text("التالي")').first();
        if (await nextBtn3.isVisible() && await nextBtn3.isEnabled()) {
          await nextBtn3.click();
          await waitForAngular(page);
          await snap(page, S, '2.2-wizard-step4-starting-point', testInfo);
        }
      }
    }
  });

  test('2.3 Open Template in Canvas Editor', async ({ page }, testInfo) => {
    await navigateTo(page, '/templates', testInfo);
    await waitForSpinner(page);

    // Click first template's designer button
    const designerLink = page.locator('a[routerlink*="designer"], button:has-text("Designer"), button:has-text("المصمم")').first();
    if (await designerLink.isVisible()) {
      await designerLink.click();
      await waitForAngular(page);
      await page.waitForTimeout(2000); // Canvas needs time to render
      await snap(page, S, '2.3-canvas-editor', testInfo);
    } else {
      // Try clicking the first template card
      const card = page.locator('mat-card').first();
      if (await card.isVisible()) {
        await card.click();
        await waitForAngular(page);
        await page.waitForTimeout(2000);
        await snap(page, S, '2.3-canvas-editor', testInfo);
      }
    }
  });
});
